Add Database Cleanup Scripts
boklisten/bl-cron pull request #1
Opened 2023-11-22 15:34 UTC by AdrianAndersen

NB: when you test these - make sure to change to /staging!!

2023-11-23 15:40 UTC, LarsSelbekk requested changes

2023-11-23 15:40 UTC, LarsSelbekk commented on database_cleanup/remove_old_order_references.sh
> +        $merge: {
I'm not sure whether this can cause concurrency issues. You read the orders, edit, then write back everything. What happens if another write happens in the meantime? Is that possible? Please make sure that either the aggregation locks the orders collection for the entire run, or try to rewrite the aggregation so it has less damage potential.

2023-11-29 08:47 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Hente ut inaktive brukere](https://trello.com/c/nJLMxchI/852-hente-ut-inaktive-brukere)

2024-01-31 15:23 UTC, AdrianAndersen commented on database_cleanup/Dockerfile
> +CMD ["sh", "/remove_unplaced_orders.sh"]
Split into 2

2024-01-31 15:24 UTC, AdrianAndersen commented on database_cleanup/Dockerfile
> +COPY dump_and_restore.sh /
Yup, I stupid sumtimes

2024-01-31 15:24 UTC, AdrianAndersen commented on database_cleanup/remove_old_order_references.sh
> +        $merge: {
We will do it in the middle of the night, should not be an issue really. If you have a suggestion for a way to do this, please let me know, but otherwise I think it should be fine

2024-02-07 13:54 UTC, LarsSelbekk requested changes
The actual commands work well, though it might be better to change as requested. Also, the Dockerfile doesn't work because the command `mongo` isn't included in the `mongodb-tools`, so it won't work in prod.

2024-02-07 13:54 UTC, LarsSelbekk commented on database_cleanup/remove_unplaced_orders/remove_unplaced_orders.sh
> +mongo "${MONGO_URL}/production" --eval 'db.orders.remove({ placed: false, creationTime: {$lt: new Date(new Date().setFullYear(new Date().getFullYear() - 1))}})'
Also, I was surprised that you had to do an extra `new Date()`, but I guess for some reason `setFullYear` returns the timestamp, so nvm I guess you have to do it that way.

2024-02-07 13:54 UTC, LarsSelbekk commented on database_cleanup/remove_unplaced_orders/Dockerfile
> +RUN apk add --no-cache mongodb-tools
`mongodb-tools` does not contain the `mongo` command. You'll have to figure out how to install it yourself, from my searching it doesn't appear to be included in alpine's package manager anymore. [This npm package](https://www.npmjs.com/package/mongosh) does seem to be an official way to get `mongosh`. It could also be a good idea to use the actual JS client library to get syntax highlighting and stuff and linting and stuff, but that would be more complicated and probably best solved by moving the bl-cron scripts to bl-api, so I do not expect it.

2024-02-07 13:54 UTC, LarsSelbekk commented on database_cleanup/remove_old_order_references/remove_old_order_references.sh
> +    }
This is a possibly less destructive way to do it; it will only change the `orders` field. You can decide if you prefer it or not. I do think the `whenNotMatched: "discard"` should be included either way, as we otherwise may restore deleted objects. Just for good practice.

```suggestion
    {
        $project: {
            orders: 1,
        },
    },
    {
        $merge: {
            into: "userdetails",
            whenNotMatched: "discard"
        },
    }
```

2024-02-21 15:00 UTC, merged